- name: config mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: start and enable the mysql server
    ansible.builtin.service:
      name: mysqld
      state: start
      enabled: yes
