- name: config mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql libraries
    ansible.builtin.pip:
      name: PyMysql
      executable: pip3.9
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: start and enable the mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to the my sql server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.kishan.store
    register: mysql_info

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"