- name: config mysql server
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: install mysql libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
      - PyMysql
      - cryptography
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: start and enable the mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to the my sql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: mysql.kishan.store
    register: mysql_info
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: set root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true